version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: ssavboy/backend_foodgram:latest
    restart: always
    ports:
     - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: ssavboy/frontend_foodgram:v1.0
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend

volumes:
  static_value:
  media_value:
  db_value: